id: IC493900F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:19:02+00:00'
last_modified: '2022-06-07T21:04:53.733424+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137817
  title: 'བློ་གསར་ཤེས་སྟེགས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    06EA:
      image_group_id: I2PD19063
      title: ''
      total_pages: 320
      order: 1
      base_file: 06EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
