id: P004208
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137817
  title: 'བློ་གསར་ཤེས་སྟེགས། '
  author: ''
  volumes:
    5dc4e90be0124cbda1c1372b69c8ee39:
      image_group_id: I2PD19063
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
